apiVersion: constraints.gatekeeper.sh/v1beta1
kind: HPAReplicaConstraint
metadata:
  name: deployment-statefulset-hpa-replica-constraint
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
      - apiGroups: ["apps"]
        kinds: ["StatefulSet"]
